<Project Sdk="Godot.NET.Sdk/4.5.1">
  <Import Project="GameRefs.props" />

  <PropertyGroup>
    <AssemblyName>fat_baby</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(Sts2Dll)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BaseLib">
      <HintPath>$(BaseLibDll)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(HarmonyDll)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
